const K={tasks:'attentionos.tasks.v1',sessions:'attentionos.sessions.v1',active:'attentionos.active.v1'};const $=id=>document.getElementById(id);const load=k=>{try{const v=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(v)?v:[]}catch{return[]}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));let timerId=null,active=null,interrupts=0;
function fmt(s){return`${String(Math.floor(Math.max(0,s)/60)).padStart(2,'0')}:${String(Math.max(0,s)%60).padStart(2,'0')}`}
function setControls(on){$('start25').disabled=on;$('start45').disabled=on;$('stopBtn').disabled=!on;$('interruptBtn').disabled=!on}
function remainingSeconds(){if(!active)return 1500;return Math.max(0,Math.ceil((active.endsAt-Date.now())/1000))}
function persistActive(){if(active)localStorage.setItem(K.active,JSON.stringify({...active,interruptions:interrupts}));else localStorage.removeItem(K.active)}
function render(){const tasks=load(K.tasks),sessions=load(K.sessions),sum=AttentionOS.summarize(sessions);$('recommendation').textContent=AttentionOS.recommend(tasks,sessions);$('focusMinutes').textContent=sum.minutes;$('focusScore').textContent=sum.avgFocus??'—';$('interruptions').textContent=sum.interruptions;$('bestHour').textContent=sum.bestHour===null?'—':`${String(sum.bestHour).padStart(2,'0')}:00`;$('tasks').innerHTML='';AttentionOS.rankTasks(tasks).forEach(t=>{const d=document.createElement('div');d.className='item';d.innerHTML='<div><b></b><small></small></div><button class="score ghost" type="button" aria-label="Delete task"></button>';d.querySelector('b').textContent=t.title;d.querySelector('small').textContent=`Impact ${t.impact} · urgency ${t.urgency} · effort ${t.effort}`;const del=d.querySelector('.score');del.textContent=`${AttentionOS.scoreTask(t)} ×`;del.onclick=()=>{save(K.tasks,tasks.filter(x=>x.id!==t.id));render()};$('tasks').appendChild(d)});$('sessions').innerHTML='';sessions.slice(-5).reverse().forEach(s=>{const d=document.createElement('div');d.className='item';d.innerHTML='<div><b></b><small></small></div><span class="score"></span>';d.querySelector('b').textContent=`${s.minutes} min focus`;d.querySelector('small').textContent=`${new Date(s.startedAt).toLocaleString()} · ${s.interruptions} interruption(s) · ${s.completed?'completed':'stopped'}`;d.querySelector('.score').textContent=AttentionOS.focusScore(s);$('sessions').appendChild(d)});const trend=AttentionOS.weeklyTrend(sessions);$('weekTrend').innerHTML='';trend.forEach(day=>{const d=document.createElement('div');d.className='item';d.innerHTML='<div><b></b><small></small></div><span class="score"></span>';d.querySelector('b').textContent=new Date(`${day.date}T12:00:00`).toLocaleDateString(undefined,{weekday:'short'});d.querySelector('small').textContent=`${day.sessions} session${day.sessions===1?'':'s'} · ${day.interruptions} interruption${day.interruptions===1?'':'s'}`;d.querySelector('.score').textContent=`${day.minutes}m`;$('weekTrend').appendChild(d)});$('insight').textContent=sum.sessions<3?'Log at least three real sessions before treating any pattern as meaningful.':`Across ${sum.sessions} sessions, you logged ${sum.minutes} focused minutes. ${sum.bestHour!==null?`Your strongest observed hour is around ${String(sum.bestHour).padStart(2,'0')}:00.`:''}`}
$('taskForm').onsubmit=e=>{e.preventDefault();const title=$('taskTitle').value.trim();if(!title)return;const tasks=load(K.tasks);tasks.push({id:crypto.randomUUID(),title,impact:+$('impact').value,urgency:+$('urgency').value,effort:+$('effort').value});save(K.tasks,tasks);e.target.reset();render()};
function tick(){if(!active)return;const remaining=remainingSeconds();$('timer').textContent=fmt(remaining);if(remaining<=0)finish(true)}
function start(min){if(active)return;interrupts=0;active={startedAt:new Date().toISOString(),planned:min,endsAt:Date.now()+min*60000};persistActive();$('timerState').textContent='Focusing';setControls(true);tick();timerId=setInterval(tick,1000)}
function finish(completed){if(!active)return;clearInterval(timerId);const elapsed=Math.max(1,Math.min(active.planned,Math.round((Date.now()-new Date(active.startedAt).getTime())/60000)));const sessions=load(K.sessions);sessions.push({startedAt:active.startedAt,minutes:completed?active.planned:elapsed,interruptions:interrupts,completed});save(K.sessions,sessions);active=null;persistActive();$('timerState').textContent=completed?'Complete':'Stopped & saved';$('timer').textContent='00:00';setControls(false);render()}
$('start25').onclick=()=>start(25);$('start45').onclick=()=>start(45);$('stopBtn').onclick=()=>finish(false);$('interruptBtn').onclick=()=>{if(active){interrupts++;persistActive();$('timerState').textContent=`Focusing · ${interrupts} interruption${interrupts===1?'':'s'}`}};
$('exportBtn').onclick=()=>{const data=JSON.stringify({version:1,exportedAt:new Date().toISOString(),tasks:load(K.tasks),sessions:load(K.sessions)},null,2);const u=URL.createObjectURL(new Blob([data],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='attentionos-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),500)};
$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text()),clean=AttentionOS.validateImport(parsed);save(K.tasks,clean.tasks);save(K.sessions,clean.sessions);$('dataStatus').textContent=`Restored ${clean.tasks.length} tasks and ${clean.sessions.length} sessions.`;render()}catch(err){$('dataStatus').textContent=err.message}finally{e.target.value=''}};
try{const saved=JSON.parse(localStorage.getItem(K.active)||'null');if(saved&&Number(saved.endsAt)>Date.now()){active=saved;interrupts=Math.max(0,Number(saved.interruptions)||0);setControls(true);$('timerState').textContent='Focusing · restored after reload';tick();timerId=setInterval(tick,1000)}else if(saved){const sessions=load(K.sessions),elapsed=Math.max(1,Math.min(Number(saved.planned)||1,Math.round((Date.now()-new Date(saved.startedAt).getTime())/60000)));sessions.push({startedAt:saved.startedAt,minutes:elapsed,interruptions:Math.max(0,Number(saved.interruptions)||0),completed:false});save(K.sessions,sessions);localStorage.removeItem(K.active);$('dataStatus').textContent='Recovered an expired in-progress block as stopped, not completed.'}}catch{localStorage.removeItem(K.active)}render();