(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.AttentionOS=api;})(typeof self!=='undefined'?self:this,function(){
function clamp(n,a,b){return Math.min(b,Math.max(a,n))}
function scoreTask(t){const impact=clamp(Number(t.impact)||1,1,5),urgency=clamp(Number(t.urgency)||1,1,5),effort=clamp(Number(t.effort)||1,1,5);return Math.round((impact*2+urgency*1.5+(6-effort))*10)/10}
function rankTasks(tasks){return [...(tasks||[])].sort((a,b)=>scoreTask(b)-scoreTask(a))}
function focusScore(s){const mins=Math.max(0,Number(s.minutes)||0),ints=Math.max(0,Number(s.interruptions)||0),completed=!!s.completed;return clamp(Math.round((Math.min(mins,90)/90*70)+(completed?20:0)-ints*6+10),0,100)}
function validDate(v){const d=new Date(v);return Number.isFinite(d.getTime())?d:null}
function avg(xs){return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0}
function summarize(sessions){const xs=(sessions||[]).filter(Boolean);if(!xs.length)return{sessions:0,minutes:0,avgFocus:null,interruptions:0,bestHour:null};const minutes=xs.reduce((a,s)=>a+(Number(s.minutes)||0),0),interruptions=xs.reduce((a,s)=>a+(Number(s.interruptions)||0),0);const avgFocus=Math.round(xs.reduce((a,s)=>a+focusScore(s),0)/xs.length);const hours={};xs.forEach(s=>{const d=validDate(s.startedAt);if(!d)return;const h=d.getHours();(hours[h]??=[]).push(focusScore(s))});const bestHour=Object.entries(hours).sort((a,b)=>avg(b[1])-avg(a[1]))[0]?.[0]??null;return{sessions:xs.length,minutes,avgFocus,interruptions,bestHour}}
function weeklyTrend(sessions,now=new Date()){const end=new Date(now);end.setHours(23,59,59,999);const start=new Date(end);start.setDate(start.getDate()-6);start.setHours(0,0,0,0);const days=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return{date:d.toISOString().slice(0,10),minutes:0,sessions:0,interruptions:0}});(sessions||[]).forEach(s=>{const d=validDate(s.startedAt);if(!d||d<start||d>end)return;const key=d.toISOString().slice(0,10),row=days.find(x=>x.date===key);if(row){row.minutes+=Math.max(0,Number(s.minutes)||0);row.sessions++;row.interruptions+=Math.max(0,Number(s.interruptions)||0)}});return days}
function recommend(tasks,sessions){const ranked=rankTasks(tasks),summary=summarize(sessions),first=ranked[0];if(!first)return'Add one meaningful task, then start a short focus block.';if(summary.sessions<3)return`Next: ${first.title}. Try 25 focused minutes. Log a few real sessions before adapting the duration.`;const length=summary.avgFocus<55?20:summary.avgFocus>80?45:30;return`Next: ${first.title}. Try ${length} focused minutes, then review.`}
function validateImport(data){if(!data||data.version!==1||!Array.isArray(data.tasks)||!Array.isArray(data.sessions))throw new Error('Unsupported AttentionOS backup.');const tasks=data.tasks.filter(t=>t&&typeof t.title==='string').slice(0,500).map(t=>({id:String(t.id||''),title:t.title.trim().slice(0,100),impact:clamp(Number(t.impact)||1,1,5),urgency:clamp(Number(t.urgency)||1,1,5),effort:clamp(Number(t.effort)||1,1,5)})).filter(t=>t.title);const sessions=data.sessions.filter(s=>s&&validDate(s.startedAt)).slice(-2000).map(s=>({startedAt:new Date(s.startedAt).toISOString(),minutes:clamp(Number(s.minutes)||0,0,1440),interruptions:clamp(Number(s.interruptions)||0,0,1000),completed:!!s.completed}));return{tasks,sessions}}
return{scoreTask,rankTasks,focusScore,summarize,weeklyTrend,recommend,validateImport};});