(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ClearFlowAnalysis=api;})(typeof self!=='undefined'?self:this,function(){'use strict';
function real(rows){return (Array.isArray(rows)?rows:[]).filter(r=>r&&!r.isDemo)}
function wilson(successes,n,z=1.96){if(!Number.isInteger(n)||n<0||successes<0||successes>n)throw new Error('Invalid binomial counts');if(!n)return null;const p=successes/n,z2=z*z,d=1+z2/n,c=(p+z2/(2*n))/d,h=z*Math.sqrt((p*(1-p)+z2/(4*n))/n)/d;return{estimate:p,low:Math.max(0,c-h),high:Math.min(1,c+h),n}}
function median(a){const x=a.filter(Number.isFinite).slice().sort((a,b)=>a-b);if(!x.length)return null;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2}
function hashSeed(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let x=seed>>>0;return()=>{x=(Math.imul(1664525,x)+1013904223)>>>0;return x/4294967296}}
function bootstrapMedianCI(values,iterations=2000,seed='clearflow'){const v=values.filter(Number.isFinite);if(!v.length)return null;if(v.length===1)return{estimate:v[0],low:v[0],high:v[0],n:1,iterations:0};const r=rng(hashSeed(seed)),stats=[];for(let k=0;k<iterations;k++){const sample=[];for(let i=0;i<v.length;i++)sample.push(v[Math.floor(r()*v.length)]);stats.push(median(sample))}stats.sort((a,b)=>a-b);const q=p=>stats[Math.min(stats.length-1,Math.max(0,Math.floor(p*(stats.length-1))))];return{estimate:median(v),low:q(.025),high:q(.975),n:v.length,iterations}}
function group(rows,key){const m=new Map;for(const r of real(rows)){const k=String(r[key]??'unknown').trim()||'unknown';if(!m.has(k))m.set(k,[]);m.get(k).push(r)}return [...m.entries()].map(([name,items])=>summarize(items,name))}
function summarize(rows,label='all'){const x=real(rows),n=x.length,s=x.filter(r=>r.outcome==='success').length,j=x.filter(r=>r.jammed===true).length,d=x.filter(r=>r.outcome==='success'&&Number.isFinite(r.durationSeconds)).map(r=>r.durationSeconds);return{label,n,successes:s,jams:j,successCI:wilson(s,n),jamCI:wilson(j,n),successDurationCI:bootstrapMedianCI(d,2000,'duration:'+label)}}
function compareToolHeads(rows){return group(rows,'toolHead').sort((a,b)=>b.n-a.n||a.label.localeCompare(b.label))}
function compareBlockages(rows){return group(rows,'blockage').sort((a,b)=>b.n-a.n||a.label.localeCompare(b.label))}
function evidenceGate(rows,{minTrials=10,minPerTool=3,maxJamRate=.2,minSuccessRate=.7}={}){const all=summarize(rows),tools=compareToolHeads(rows),reasons=[];if(all.n<minTrials)reasons.push(`Need ${minTrials-all.n} more real trial(s) for minimum sample size.`);for(const t of tools)if(t.n<minPerTool)reasons.push(`${t.label}: ${minPerTool-t.n} more trial(s) needed for per-tool minimum.`);if(all.successCI&&all.successCI.low<minSuccessRate)reasons.push(`95% lower confidence bound for success (${(all.successCI.low*100).toFixed(1)}%) is below ${(minSuccessRate*100).toFixed(0)}%.`);if(all.jamCI&&all.jamCI.high>maxJamRate)reasons.push(`95% upper confidence bound for jam rate (${(all.jamCI.high*100).toFixed(1)}%) exceeds ${(maxJamRate*100).toFixed(0)}%.`);return{pass:reasons.length===0,reasons,summary:all,tools,thresholds:{minTrials,minPerTool,maxJamRate,minSuccessRate}}}
function report(rows,opts){const gate=evidenceGate(rows,opts);return{generatedAt:new Date().toISOString(),evidenceGate:gate,byToolHead:gate.tools,byBlockage:compareBlockages(rows),note:'Confidence intervals quantify uncertainty in recorded controlled trials; they do not establish field safety or municipal readiness.'}}
return{wilson,bootstrapMedianCI,summarize,compareToolHeads,compareBlockages,evidenceGate,report};});
