const KEY="clearflow.validation.trials.v1";const $=id=>document.getElementById(id);
function loadTrials(){try{const parsed=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(parsed)?parsed:[]}catch{return[]}}
function saveTrials(trials){localStorage.setItem(KEY,JSON.stringify(trials))}
function formatPct(value){return value===null?"—":`${Math.round(value*100)}%`}function formatDuration(value){return Number.isFinite(value)?`${value.toFixed(1)} s`:"—"}
function render(){const trials=loadTrials();const m=ClearFlowValidation.metrics(trials);$("totalTrials").textContent=String(m.total);$("successRate").textContent=formatPct(m.successRate);$("medianTime").textContent=m.medianSuccessSeconds===null?"—":`${m.medianSuccessSeconds.toFixed(1)} s`;$("jamRate").textContent=formatPct(m.jamRate);$("trialRows").innerHTML="";$("emptyState").hidden=trials.length>0;trials.slice().reverse().forEach((t,ri)=>{const tr=document.createElement("tr");[String(trials.length-ri)+(t.isDemo?" demo":""),new Date(t.recordedAt).toLocaleString(),t.toolHead,t.blockage,t.outcome,formatDuration(t.durationSeconds),t.jammed?"Yes":"No",t.cameraUseful===null?"Not tested":t.cameraUseful?"Yes":"No",t.notes||"—"].forEach(value=>{const td=document.createElement("td");td.textContent=value;tr.appendChild(td)});const td=document.createElement("td");const btn=document.createElement("button");btn.className="ghost";btn.type="button";btn.textContent="Delete";btn.addEventListener("click",()=>{saveTrials(loadTrials().filter(x=>x.id!==t.id));render()});td.appendChild(btn);tr.appendChild(td);$("trialRows").appendChild(tr)})}
$("trialForm").addEventListener("submit",e=>{e.preventDefault();try{const trial=ClearFlowValidation.sanitizeTrial({toolHead:$("toolHead").value,blockage:$("blockage").value,durationSeconds:$("duration").value,outcome:$("outcome").value,jammed:$("jammed").value,cameraUseful:$("cameraUseful").value,notes:$("notes").value});const trials=loadTrials();trials.push(trial);saveTrials(trials);e.target.reset();$("formMessage").textContent="Saved locally.";render()}catch(err){$("formMessage").textContent=err.message}});
$("sampleBtn").addEventListener("click",()=>{const demo=ClearFlowValidation.sanitizeTrial({id:`demo-${Date.now()}`,toolHead:"Silt brush",blockage:"DEMO ONLY: wet silt surrogate",durationSeconds:18.4,outcome:"partial",jammed:"no",cameraUseful:"yes",notes:"Demo record for interface preview. Excluded from all summary metrics.",isDemo:true});const trials=loadTrials();trials.push(demo);saveTrials(trials);render()});
function download(filename,text,type){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$("exportCsv").addEventListener("click",()=>download("clearflow-validation.csv",ClearFlowValidation.toCsv(loadTrials()),"text/csv"));$("exportJson").addEventListener("click",()=>download("clearflow-validation.json",JSON.stringify(loadTrials(),null,2),"application/json"));
$("clearAll").addEventListener("click",()=>{if(confirm("Delete all locally stored ClearFlow validation records in this browser?")){localStorage.removeItem(KEY);render()}});render();
