(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;else root.ClearFlowValidation=api;})(typeof self!=="undefined"?self:this,function(){"use strict";
const OUTCOMES=new Set(["success","partial","fail"]);const YESNO=new Set(["yes","no"]);
function cleanText(value,max=500){return String(value??"").trim().slice(0,max)}
function cryptoSafeId(now=new Date()){return `${now.getTime().toString(36)}-${Math.random().toString(36).slice(2,10)}`}
function sanitizeTrial(input,now=new Date()){const durationRaw=input.durationSeconds;const duration=durationRaw===""||durationRaw===null||durationRaw===undefined?null:Number(durationRaw);if(!cleanText(input.toolHead,80))throw new Error("Tool head is required.");if(!cleanText(input.blockage,100))throw new Error("Blockage surrogate is required.");if(!OUTCOMES.has(input.outcome))throw new Error("Valid outcome is required.");if(!YESNO.has(input.jammed))throw new Error("Jam/stall observation is required.");if(duration!==null&&(!Number.isFinite(duration)||duration<0||duration>86400))throw new Error("Duration must be a valid non-negative number.");const cameraUseful=input.cameraUseful===""||input.cameraUseful==null?null:input.cameraUseful;if(cameraUseful!==null&&!YESNO.has(cameraUseful))throw new Error("Camera usefulness must be yes, no, or untested.");return{id:cleanText(input.id,80)||cryptoSafeId(now),recordedAt:input.recordedAt||now.toISOString(),toolHead:cleanText(input.toolHead,80),blockage:cleanText(input.blockage,100),durationSeconds:duration,outcome:input.outcome,jammed:input.jammed==="yes",cameraUseful:cameraUseful===null?null:cameraUseful==="yes",notes:cleanText(input.notes,500),isDemo:Boolean(input.isDemo)}}
function realTrials(trials){return(Array.isArray(trials)?trials:[]).filter(t=>t&&!t.isDemo)}
function median(values){const nums=(values||[]).filter(Number.isFinite).slice().sort((a,b)=>a-b);if(!nums.length)return null;const m=Math.floor(nums.length/2);return nums.length%2?nums[m]:(nums[m-1]+nums[m])/2}
function metrics(trials){const rows=realTrials(trials);const total=rows.length;const successes=rows.filter(t=>t.outcome==="success").length;const jams=rows.filter(t=>t.jammed===true).length;const successfulDurations=rows.filter(t=>t.outcome==="success"&&Number.isFinite(t.durationSeconds)).map(t=>t.durationSeconds);return{total,successRate:total?successes/total:null,jamRate:total?jams/total:null,medianSuccessSeconds:median(successfulDurations),successfulMeasuredTrials:successfulDurations.length}}
function csvEscape(value){const str=value===null||value===undefined?"":String(value);return/[",\n]/.test(str)?`"${str.replace(/"/g,'""')}"`:str}
function toCsv(trials){const headers=["id","recordedAt","toolHead","blockage","outcome","durationSeconds","jammed","cameraUseful","notes","isDemo"];const lines=[headers.join(",")];for(const t of Array.isArray(trials)?trials:[])lines.push(headers.map(h=>csvEscape(t[h])).join(","));return lines.join("\n")}
function claimSummary(trials){const m=metrics(trials);if(!m.total)return"No real controlled trials recorded.";const pct=v=>`${Math.round(v*100)}%`;const parts=[`${m.total} real controlled trial${m.total===1?"":"s"} recorded`,`${pct(m.successRate)} fully cleared`,`${pct(m.jamRate)} with a jam/stall observation`];if(m.medianSuccessSeconds!==null)parts.push(`median ${m.medianSuccessSeconds.toFixed(1)} s among successful measured trials`);return parts.join("; ")+ "."}
return{sanitizeTrial,realTrials,median,metrics,toCsv,claimSummary};});
